/* ============================================================
   iLearn — Confident Computing course content
   16 lessons · exactly 15 activities each (240 total)
   Activity types:
     pick     — multiple choice   {q, type:'pick', ok, hint?, options:[{t,ok?,s?}]}
     type     — typing check      {q, type:'type', placeholder, answer?, ok, hint?}
     practice — real-computer task {q, type:'practice', minutes, detail, evidence}
   Mirrors the server course-content.js shape so it maps straight back.
   ============================================================ */

export const course = {
  slug: 'confident-computing',
  title: 'Confident Computing',
  description: 'Build practical computer confidence from first sign-in through everyday Word and Excel tasks, one calm step at a time.',
  lessons: [
    {
      title: 'Turn on and sign in',
      goal: 'Switch the computer on, sign in safely, and recognise the desktop.',
      outcome: 'I can turn the computer on, wait calmly, sign in, and know I have reached the desktop.',
      tutor: 'In this lesson, I will guide you through the full start-up routine. We press the power button once, wait calmly, sign in carefully, and check that the desktop is ready. There is no rush — waiting is part of using a computer well.',
      steps: ['Find the power button and press it once', 'Wait calmly while the computer starts', 'Type the password carefully', 'Check the desktop has appeared', 'If ready: find the safe shut-down option'],
      carer: 'Let the learner set the pace. Waiting for the machine to load is a skill in itself. Offer one prompt at a time, then wait. Praise calm waiting, not speed.',
      tasks: [
        { q: 'Staff setup: prepare the real computer before the learner starts.', type: 'practice', minutes: 5, detail: 'Check the device is charged, the keyboard and mouse are connected, and the learner can sit comfortably with the screen at a good distance.', evidence: 'Staff can describe any access needs before the task begins.' },
        { q: 'Which control turns the computer on?', type: 'pick', ok: 'Correct. The power control starts the computer.', hint: 'Look for the option that says Power.', options: [{ t: 'Power', ok: true, s: 'key' }, { t: 'Volume', s: 'key' }, { t: 'Brightness', s: 'key' }] },
        { q: 'Which symbol marks the power button?', type: 'pick', ok: 'Yes — a circle with a small line through the top.', hint: 'It looks like a circle that is not quite closed, with a line at the top.', options: [{ t: 'A circle with a line at the top', ok: true }, { t: 'A lightning bolt' }, { t: 'A sun symbol' }, { t: 'A plus sign' }] },
        { q: 'What should you do while the computer is still starting?', type: 'pick', ok: 'Correct. Waiting calmly is part of starting a computer safely.', options: [{ t: 'Wait calmly', ok: true }, { t: 'Press every key quickly' }, { t: 'Turn it off and on again' }, { t: 'Type your password before it asks' }] },
        { q: 'Guided routine: turn on, wait, sign in and point to the desktop.', type: 'practice', minutes: 10, detail: 'Complete the full start-up routine twice. First time with staff prompts, second time with fewer prompts.', evidence: 'Learner reaches the desktop and names or points to one thing they recognise.' },
        { q: 'Type a practice password to sign in:', type: 'type', placeholder: 'Type here', ok: 'Good. That is the careful pace we use when signing in.' },
        { q: 'Why do we sign in with a password?', type: 'pick', ok: 'Correct. It keeps your account and work private, so only you can open it.', hint: 'Think about who should be able to see your work.', options: [{ t: 'So only you can open your account and work', ok: true }, { t: 'To make the computer start up faster' }, { t: 'To connect to the internet' }, { t: 'To turn the volume up' }] },
        { q: 'After signing in, the main screen with your background and icons is called the…', type: 'pick', ok: 'Correct. That is the desktop — your starting place.', hint: 'It is where your programs and folders live.', options: [{ t: 'Desktop', ok: true }, { t: 'Home page' }, { t: 'Dashboard' }, { t: 'Login screen' }] },
        { q: 'Independence practice: start from a signed-out screen.', type: 'practice', minutes: 8, detail: 'Staff signs out, then the learner signs back in with only one prompt at a time. Pause after each prompt so they can think.', evidence: 'Record whether the learner needed physical, gesture, verbal or no support.' },
        { q: 'Reflection: type one thing you can see on the desktop.', type: 'type', placeholder: 'Start menu', ok: 'Good noticing. Recognising the desktop builds confidence.' },
        { q: 'You type your password and it says it is wrong. What is the best thing to do?', type: 'pick', ok: 'Correct. Stay calm and type it again, carefully — mistakes are fine.', hint: 'Slow and calm works better than fast.', options: [{ t: 'Type it again slowly and carefully', ok: true }, { t: 'Press Enter many times quickly' }, { t: 'Turn the computer off and on' }, { t: 'Type it much faster' }] },
        { q: 'Where do we look to switch the computer off safely?', type: 'pick', ok: 'Correct. The Start menu has the safe shut-down option.', options: [{ t: 'The Start menu', ok: true }, { t: 'The Recycle Bin' }, { t: 'The Volume button' }] },
        { q: 'Stretch: find the safe "Shut down" option with support.', type: 'practice', minutes: 6, detail: 'Open the Start menu, find the power option, and identify Shut down. Staff can complete the final click if needed.', evidence: 'Learner can find the power menu again when asked.' },
        { q: 'Type the word that means switching the computer off safely:', type: 'type', placeholder: 'shut down', answer: 'shut', ok: 'Correct. We always shut down safely, not by pulling the plug.' },
        { q: 'How do you know the computer has finished starting and is ready?', type: 'pick', ok: 'Correct. When the desktop with your icons appears, it is ready.', hint: 'One of these actually means it is NOT ready yet.', options: [{ t: 'The desktop with your icons appears', ok: true }, { t: 'A password box is still showing' }, { t: 'The screen is still black' }, { t: 'The fan is still whirring' }] },
      ],
    },
    {
      title: 'Use the mouse and click',
      goal: 'Move the pointer, click once, and choose an item on screen.',
      outcome: 'I can move the pointer where I want and click once to choose something.',
      tutor: 'In this lesson, we practise using the mouse. Watch the pointer as it moves, stop on the thing you want, then click once. We are aiming for calm, gentle control, not speed.',
      steps: ['Rest your hand gently on the mouse', 'Move the mouse and watch the pointer move', 'Point to the item you want', 'Click once to choose it', 'If ready: right-click, then click away to close the menu'],
      carer: 'Check mouse position and grip first. If hand movement is difficult, guide at the wrist, then reduce support. Note whether difficulty is speed, aim, or confidence.',
      tasks: [
        { q: 'Warm-up: move the pointer to all four corners of the screen.', type: 'practice', minutes: 8, detail: 'Ask the learner to move slowly to top-left, top-right, bottom-left and bottom-right. Repeat until movement is calmer.', evidence: 'Pointer movement becomes more controlled by the end.' },
        { q: 'The arrow on the screen is called the…', type: 'pick', ok: 'Correct. The arrow is the pointer.', options: [{ t: 'Pointer', ok: true }, { t: 'The mouse' }, { t: 'The screen' }, { t: 'The keyboard' }] },
        { q: 'Click once on the Word app.', type: 'pick', ok: 'Yes. One click chooses the item.', hint: 'Word is the blue W.', options: [{ t: 'W', ok: true, s: 'icon-w' }, { t: 'X', s: 'icon-x' }, { t: 'Bin', s: 'icon' }] },
        { q: 'How many clicks do we use to choose something?', type: 'pick', ok: 'Correct. One single click chooses something.', options: [{ t: 'One click', ok: true }, { t: 'Two quick clicks' }, { t: 'A long press' }, { t: 'Five clicks' }] },
        { q: 'Accuracy practice: click five named targets.', type: 'practice', minutes: 10, detail: 'Use real icons or safe blank desktop space. Staff names a target, learner moves to it and single-clicks once.', evidence: 'Count how many clicks landed on the intended target.' },
        { q: 'Which click chooses something without opening it?', type: 'pick', ok: 'Correct. One click chooses.', options: [{ t: 'One click', ok: true }, { t: 'Double-click' }, { t: 'Hold the button down' }] },
        { q: 'Type the word "click":', type: 'type', placeholder: 'click', answer: 'click', ok: 'Correct. That word matches today’s skill.' },
        { q: 'Which button do we usually press on the mouse to choose?', type: 'pick', ok: 'Correct. We use the left button to choose.', options: [{ t: 'The left button', ok: true }, { t: 'The right button' }, { t: 'The wheel' }] },
        { q: 'Real-world practice: open the Start menu and choose a pinned app.', type: 'practice', minutes: 10, detail: 'Learner single-clicks Start, points to an app, and clicks once to choose it. Close the menu and repeat.', evidence: 'Learner can explain that one click chooses.' },
        { q: 'When the pointer becomes a hand, it usually means…', type: 'pick', ok: 'Correct. A hand means you can click there.', options: [{ t: 'You can click here', ok: true }, { t: 'Stop moving' }, { t: 'The mouse is broken' }] },
        { q: 'If the pointer moves too fast, the best thing to do is…', type: 'pick', ok: 'Correct. Move slowly and steadily.', options: [{ t: 'Move slowly and steadily', ok: true }, { t: 'Lift the mouse and shake it' }, { t: 'Press harder' }] },
        { q: 'Type the word for the arrow you move on screen:', type: 'type', placeholder: 'pointer', answer: 'point', ok: 'Good. The pointer is how we reach things.' },
        { q: 'Right-click practice: open a menu, then click away to close it.', type: 'practice', minutes: 8, detail: 'Show that right-click opens a small menu of choices. Clicking away closes it. Keep this calm and low-pressure.', evidence: 'Learner sees the difference between left-click and right-click.' },
        { q: 'To close a menu you opened by mistake, you can…', type: 'pick', ok: 'Correct. Clicking away closes the menu.', options: [{ t: 'Click away from it', ok: true }, { t: 'Turn off the computer' }, { t: 'Keep clicking it' }] },
        { q: 'Independent round: staff names three targets only.', type: 'practice', minutes: 8, detail: 'Staff says the target name but avoids pointing. Move back to gesture prompts only if the learner gets stuck.', evidence: 'Record the lowest prompt level that worked.' },
      ],
    },
    {
      title: 'Open with double-click',
      goal: 'Open a file or folder with two quick clicks.',
      outcome: 'I can open a folder or program with a double-click, and stay calm if I need to try again.',
      tutor: 'In this lesson, we learn double-clicking. Two quick clicks can open a program or file, but the mouse needs to stay still. If it does not open first time, that is fine — we pause, reset, and try again.',
      steps: ['Point at the folder or app', 'Keep the mouse still', 'Click twice quickly', 'Wait for it to open', 'If ready: double-click Word from the desktop'],
      carer: 'If double-click is tricky, note whether it is the timing, the mouse moving, or confidence. Count the rhythm if it helps: click-click.',
      tasks: [
        { q: 'Warm-up: practise the click-click rhythm away from any icon.', type: 'practice', minutes: 6, detail: 'Learner practises two quick taps on the mouse while keeping the hand still.', evidence: 'Clicks become closer together and the mouse moves less.' },
        { q: 'How do we open something from the desktop?', type: 'pick', ok: 'Correct. Two quick clicks opens it.', options: [{ t: 'Two quick clicks', ok: true }, { t: 'One single click' }, { t: 'A right-click' }, { t: 'A long press' }] },
        { q: 'What matters most during a double-click?', type: 'pick', ok: 'Correct. Keeping the mouse still helps the computer read two clicks.', options: [{ t: 'Keep the mouse still', ok: true }, { t: 'Move quickly across the screen' }, { t: 'Click slowly, once' }, { t: 'Wait ten seconds between clicks' }] },
        { q: 'Guided open: double-click Documents a few times.', type: 'practice', minutes: 10, detail: 'Open Documents, close it, then open it again. Repeat with staff fading prompts each time.', evidence: 'Learner opens the folder at least once with reduced support.' },
        { q: 'Double-click the Documents folder.', type: 'pick', ok: 'It opened. That is a confident double-click.', options: [{ t: 'Documents folder', ok: true, s: 'icon' }, { t: 'Recycle Bin', s: 'icon' }, { t: 'Downloads', s: 'icon' }, { t: 'Word', s: 'icon-w' }] },
        { q: 'A double-click is best described as…', type: 'pick', ok: 'Correct. Two quick clicks, close together.', options: [{ t: 'Two quick clicks', ok: true }, { t: 'One long press' }, { t: 'A right-click' }] },
        { q: 'If a folder does not open the first time, you should…', type: 'pick', ok: 'Correct. Calmly try the two clicks again.', options: [{ t: 'Calmly try again', ok: true }, { t: 'Click twenty times fast' }, { t: 'Restart the computer' }] },
        { q: 'Type the action we use to open an icon:', type: 'type', placeholder: 'double-click', answer: 'double', ok: 'Good. Double-click opens desktop items.' },
        { q: 'Real-world practice: open Word and close it again.', type: 'practice', minutes: 10, detail: 'Learner double-clicks Word, waits for it to open, then closes it using X with staff support.', evidence: 'Learner can say or show when the app is open.' },
        { q: 'One click chooses. Two quick clicks…', type: 'pick', ok: 'Correct. Two quick clicks opens.', options: [{ t: 'Opens', ok: true }, { t: 'Deletes' }, { t: 'Prints' }] },
        { q: 'While double-clicking, your hand should stay…', type: 'pick', ok: 'Correct. Still, so both clicks land in the same place.', options: [{ t: 'Still', ok: true }, { t: 'Moving in a circle' }, { t: 'Off the mouse' }] },
        { q: 'Type the word "open":', type: 'type', placeholder: 'open', answer: 'open', ok: 'Good. Double-click is how we open things.' },
        { q: 'Decision: which needs a double-click?', type: 'pick', ok: 'Correct. Opening a folder needs a double-click.', options: [{ t: 'Opening a folder', ok: true }, { t: 'Just choosing an icon' }, { t: 'Moving the mouse' }, { t: 'Closing a window' }] },
        { q: 'Guided close: use the X to close what you opened.', type: 'practice', minutes: 6, detail: 'After opening Word or a folder, learner finds the X in the top corner and closes it.', evidence: 'Learner locates the close button independently where possible.' },
        { q: 'Independent round: open one folder and one app.', type: 'practice', minutes: 8, detail: 'Staff names the target only. Learner attempts the double-click without hand-over-hand support unless needed.', evidence: 'Record prompt level and any motor access adjustment.' },
      ],
    },
    {
      title: 'Use the keyboard',
      goal: 'Type letters, make spaces, start a new line, and fix a mistake.',
      outcome: 'I can type words, use Space between them, start a new line, and fix a mistake with Backspace.',
      tutor: 'In this lesson, the keyboard becomes your tool for writing. We will type slowly, use Space between words, Enter for a new line, and Backspace to fix a mistake. Good typing is careful, not fast.',
      steps: ['Click where the cursor is flashing', 'Type a short word', 'Press Space to make a gap', 'Press Enter to start a new line', 'If ready: hold Shift for one capital letter'],
      carer: 'Check whether larger on-screen text is needed. Focus on Space, Enter and Backspace. Give time for visual scanning. Capitals can wait for the stretch task.',
      tasks: [
        { q: 'Warm-up: find five letters on the keyboard.', type: 'practice', minutes: 8, detail: 'Staff names letters from the learner’s name or a familiar word. Learner points first, then presses.', evidence: 'Learner scans the keyboard with less support by the end.' },
        { q: 'Type the word: cat', type: 'type', placeholder: 'Type cat', answer: 'cat', ok: 'Well done. You typed the word accurately.', hint: 'Find c, then a, then t.' },
        { q: 'Which key removes the last letter?', type: 'pick', ok: 'Correct. Backspace removes the last letter.', options: [{ t: 'Backspace', ok: true, s: 'key' }, { t: 'Enter', s: 'key' }, { t: 'Space', s: 'key' }] },
        { q: 'Which key makes a gap between words?', type: 'pick', ok: 'Correct. The Space bar makes a gap.', options: [{ t: 'Space', ok: true, s: 'key' }, { t: 'Shift', s: 'key' }, { t: 'Enter', s: 'key' }] },
        { q: 'Guided typing: type three short words.', type: 'practice', minutes: 10, detail: 'Use simple words such as cat, bus and tea. After each word, press Space before the next word.', evidence: 'Learner uses Space between words at least once.' },
        { q: 'Which key starts a new line?', type: 'pick', ok: 'Correct. Enter starts a new line.', options: [{ t: 'Enter', ok: true, s: 'key' }, { t: 'Space', s: 'key' }, { t: 'Backspace', s: 'key' }] },
        { q: 'Type the word: bus', type: 'type', placeholder: 'Type bus', answer: 'bus', ok: 'Great typing.' },
        { q: 'Mistakes when typing are…', type: 'pick', ok: 'Correct. Mistakes are completely fine — we fix them with Backspace.', options: [{ t: 'Completely fine — we can fix them', ok: true }, { t: 'Not allowed' }, { t: 'Impossible to undo' }, { t: 'A reason to give up' }] },
        { q: 'Line practice: type two words, press Enter, then type two more.', type: 'practice', minutes: 10, detail: 'Learner practises Space and Enter in a short note. Staff points only if needed.', evidence: 'Learner creates at least two lines of text.' },
        { q: 'Type a short message to practise:', type: 'type', placeholder: 'I can type today.', ok: 'Great. That is a useful message.' },
        { q: 'The flashing line that shows where letters appear is the…', type: 'pick', ok: 'Correct. The flashing line is the cursor.', options: [{ t: 'Cursor', ok: true }, { t: 'Comma' }, { t: 'Corner' }] },
        { q: 'To type a capital letter you hold…', type: 'pick', ok: 'Correct. Hold Shift for one capital letter.', options: [{ t: 'Shift', ok: true, s: 'key' }, { t: 'Space', s: 'key' }, { t: 'Enter', s: 'key' }] },
        { q: 'Type your first name:', type: 'type', placeholder: 'Type your name', ok: 'Lovely. Typing your own name is a real skill.' },
        { q: 'Backspace practice: type a word, then remove it letter by letter.', type: 'practice', minutes: 8, detail: 'Learner types a short word and uses Backspace to delete it one letter at a time. Keep it calm.', evidence: 'Learner uses Backspace deliberately to fix text.' },
        { q: 'Stretch: make one capital letter using Shift.', type: 'practice', minutes: 6, detail: 'Practise holding Shift and pressing one letter. Keep this calm; it is a stretch task.', evidence: 'Learner attempts Shift with the support level recorded.' },
      ],
    },
    {
      title: 'Open, minimise and close',
      goal: 'Open a program, control the window, and close it safely.',
      outcome: 'I can open a program, minimise and restore its window, and close it with the X.',
      tutor: 'In this lesson, we look at windows. A program opens inside a window, and the buttons at the top help us minimise, maximise, or close it. We will practise choosing the right button calmly.',
      steps: ['Open one program', 'Find the window controls in the top corner', 'Minimise the window to move it out of the way', 'Close the window with X when finished', 'If ready: reopen the program from the taskbar'],
      carer: 'If several open windows are confusing, work with one window at a time and note that in the record. Keep the screen calm.',
      tasks: [
        { q: 'Warm-up: name the three window buttons.', type: 'practice', minutes: 8, detail: 'Point to minimise, maximise and close. Explain that X means finished with this window.', evidence: 'Learner identifies X without guessing.' },
        { q: 'Which button closes a window?', type: 'pick', ok: 'Correct. X closes the window.', hint: 'Close means finished with this window.', options: [{ t: 'Minimise', s: 'win' }, { t: 'Maximise', s: 'win' }, { t: 'X Close', ok: true, s: 'win-x' }] },
        { q: 'Where are the window buttons usually found?', type: 'pick', ok: 'Correct. In the top corner of the window.', options: [{ t: 'The top corner', ok: true }, { t: 'The bottom middle' }, { t: 'On the keyboard' }] },
        { q: 'What does Minimise do?', type: 'pick', ok: 'Correct. It tucks the window out of the way without closing it.', options: [{ t: 'Tucks it out of the way', ok: true }, { t: 'Deletes it' }, { t: 'Prints it' }] },
        { q: 'Guided open-close routine.', type: 'practice', minutes: 10, detail: 'Open one app, wait, minimise it, bring it back, then close it. Repeat slowly.', evidence: 'Learner completes at least two window actions.' },
        { q: 'Which button means finished with this window?', type: 'pick', ok: 'Correct. X closes the window.', options: [{ t: 'X Close', ok: true, s: 'win-x' }, { t: 'Minimise', s: 'win' }, { t: 'Maximise', s: 'win' }] },
        { q: 'A minimised window goes to the…', type: 'pick', ok: 'Correct. It waits on the taskbar at the bottom.', options: [{ t: 'Taskbar', ok: true }, { t: 'Recycle Bin' }, { t: 'Printer' }] },
        { q: 'Type the word for the button that closes a window:', type: 'type', placeholder: 'close', answer: 'close', ok: 'Correct. Close means finished.' },
        { q: 'What is best when learning a new task?', type: 'pick', ok: 'Correct. One window keeps the screen easier to understand.', options: [{ t: 'Keep one window open', ok: true }, { t: 'Open everything at once' }, { t: 'Close every program' }, { t: 'Open ten windows' }] },
        { q: 'Screen tidying practice.', type: 'practice', minutes: 10, detail: 'Open two safe windows, then close one and keep one open. Talk about why a calm screen helps learning.', evidence: 'Learner can reduce clutter with support.' },
        { q: 'To bring a minimised window back, you…', type: 'pick', ok: 'Correct. Click it on the taskbar.', options: [{ t: 'Click it on the taskbar', ok: true }, { t: 'Restart the computer' }, { t: 'Press Backspace' }] },
        { q: 'Type the word "window":', type: 'type', placeholder: 'window', answer: 'window', ok: 'Good. A program opens inside a window.' },
        { q: 'Maximise makes a window…', type: 'pick', ok: 'Correct. Bigger, to fill the screen.', options: [{ t: 'Fill the screen', ok: true }, { t: 'Disappear' }, { t: 'Turn blue' }] },
        { q: 'Reopen practice: open a program you just closed.', type: 'practice', minutes: 6, detail: 'Learner reopens the same program from the taskbar or desktop, showing that closing is not losing.', evidence: 'Learner understands closed programs can be opened again.' },
        { q: 'Independent round: open, minimise, restore and close.', type: 'practice', minutes: 8, detail: 'Staff gives the four actions in order. Learner attempts each before staff prompts.', evidence: 'Record the lowest successful prompt level.' },
      ],
    },
    {
      title: 'Save a file',
      goal: 'Save work with a clear name in the Documents folder.',
      outcome: 'I can save my work in Documents with a clear name and find it again.',
      tutor: 'In this lesson, we save work so we can find it again later. I will show you how to write a short note, give it a clear file name, save it in Documents, close it, and open it again.',
      steps: ['Click File', 'Choose Save As', 'Type a simple file name', 'Choose Documents', 'If ready: use Ctrl + S to save changes quickly'],
      carer: 'Encourage a meaningful file name. Repeat the same save location each time until the routine is familiar. Check the learner can explain where the file went.',
      tasks: [
        { q: 'Warm-up: decide on a real file name.', type: 'practice', minutes: 6, detail: 'Pick a meaningful name such as shopping list, appointment note or my practice note.', evidence: 'Learner chooses or agrees a clear file name.' },
        { q: 'Saving your work means…', type: 'pick', ok: 'Correct. Saving keeps your work so it is not lost.', options: [{ t: 'Keeping it safe', ok: true }, { t: 'Deleting it' }, { t: 'Printing it' }] },
        { q: 'Type a clear file name:', type: 'type', placeholder: 'my first note', ok: 'Good file name. Clear names make work easier to find.' },
        { q: 'Which menu do we click first to save?', type: 'pick', ok: 'Correct. We start from the File menu.', options: [{ t: 'File', ok: true }, { t: 'Help' }, { t: 'View' }, { t: 'Insert' }] },
        { q: 'Guided save: create a note and save it in Documents.', type: 'practice', minutes: 12, detail: 'Open Word, type one sentence, use Save As, type the file name and choose Documents.', evidence: 'A file is saved with a recognisable name.' },
        { q: 'Where should we save practice work first?', type: 'pick', ok: 'Correct. Documents is the safe first place to save.', options: [{ t: 'Documents', ok: true, s: 'icon' }, { t: 'Recycle Bin', s: 'icon' }, { t: 'Random folder' }] },
        { q: 'A good file name is…', type: 'pick', ok: 'Correct. Short and clear, so you can find it again.', options: [{ t: 'Short and clear', ok: true }, { t: 'A long jumble of letters' }, { t: 'Blank' }] },
        { q: 'Type the name you would give a practice file:', type: 'type', placeholder: 'my practice note', ok: 'Good. Clear names help you find files later.' },
        { q: 'Find it again.', type: 'practice', minutes: 10, detail: 'Close Word, open Documents, and locate the saved file. Open it to confirm it is the right one.', evidence: 'Learner finds the saved file with support level recorded.' },
        { q: 'The quick keyboard shortcut to save is…', type: 'pick', ok: 'Correct. Ctrl + S saves quickly.', options: [{ t: 'Ctrl + S', ok: true, s: 'key' }, { t: 'Ctrl + P', s: 'key' }, { t: 'Ctrl + Z', s: 'key' }] },
        { q: '"Save As" lets you choose…', type: 'pick', ok: 'Correct. The name and the place to save.', options: [{ t: 'The name and place', ok: true }, { t: 'The screen colour' }, { t: 'The time' }] },
        { q: 'Type the folder we save practice work in:', type: 'type', placeholder: 'Documents', answer: 'document', ok: 'Correct. Documents is our safe first place.' },
        { q: 'If you close without saving, your new work is…', type: 'pick', ok: 'Correct. It can be lost — so we save first.', options: [{ t: 'Lost', ok: true }, { t: 'Emailed to you' }, { t: 'Made bold' }] },
        { q: 'Ctrl + S practice: make a small change and save again.', type: 'practice', minutes: 6, detail: 'Add one word to the saved note and press Ctrl + S. Show that this updates the file quietly.', evidence: 'Learner sees saving again keeps the newest version.' },
        { q: 'Stretch: change the note and save again with a new name.', type: 'practice', minutes: 6, detail: 'Use Save As to make a second copy with a different name. Talk about when two versions might be useful.', evidence: 'Learner understands the difference between Save and Save As.' },
      ],
    },
    {
      title: 'Find files and folders',
      goal: 'Open Documents, find a saved file, and understand what folders are for.',
      outcome: 'I know a file is one piece of work and a folder holds files together, and I can find my work.',
      tutor: 'In this lesson, we organise work. A file is one piece of work, and a folder is a safe place to keep related files together. We will practise putting work where it belongs.',
      steps: ['Open File Explorer', 'Choose Documents', 'Look for the file name you saved', 'Open the file to check it', 'If ready: create a new folder for practice work'],
      carer: 'Check the folder language is understood, not just the clicks. Use "a box that holds your letters" if it helps. Use real file names from the learner where possible.',
      tasks: [
        { q: 'Warm-up: sort file and folder examples.', type: 'practice', minutes: 8, detail: 'Staff says examples: holiday photo, Documents, CV, shopping folder. Learner decides file or folder.', evidence: 'Learner can explain that folders hold files.' },
        { q: 'A file is…', type: 'pick', ok: 'Correct. A file is one piece of work, like a letter.', options: [{ t: 'One piece of work', ok: true }, { t: 'A box of many things' }, { t: 'The whole computer' }] },
        { q: 'A folder helps you keep files…', type: 'pick', ok: 'Correct. Folders keep related files together.', options: [{ t: 'Organised and together', ok: true }, { t: 'Hidden forever' }, { t: 'Deleted automatically' }, { t: 'Harder to find' }] },
        { q: 'The program that shows your files is called…', type: 'pick', ok: 'Correct. File Explorer shows your files and folders.', options: [{ t: 'File Explorer', ok: true }, { t: 'The Bin' }, { t: 'The Printer' }] },
        { q: 'Guided folder tour.', type: 'practice', minutes: 10, detail: 'Open File Explorer and visit Desktop, Documents and Downloads. Keep returning to Documents as the main place.', evidence: 'Learner recognises Documents as the first place to look.' },
        { q: 'Choose the place where your saved work is usually kept.', type: 'pick', ok: 'Yes. Documents is where we look first.', options: [{ t: 'Documents', ok: true, s: 'icon' }, { t: 'Downloads only', s: 'icon' }, { t: 'The Recycle Bin', s: 'icon' }, { t: 'The taskbar' }] },
        { q: 'If a folder is a box, a file is…', type: 'pick', ok: 'Correct. A file is one letter inside the box.', options: [{ t: 'A letter inside it', ok: true }, { t: 'Another box' }, { t: 'The lid' }] },
        { q: 'Type the folder we look in first for saved work:', type: 'type', placeholder: 'Documents', answer: 'document', ok: 'Correct. Documents is our home base.' },
        { q: 'Create a practice folder.', type: 'practice', minutes: 10, detail: 'With staff support, create a new folder in Documents called Practice Work.', evidence: 'Folder is created or learner can describe the steps.' },
        { q: 'Why do we use folders?', type: 'pick', ok: 'Correct. So similar files stay together and are easy to find.', options: [{ t: 'To stay tidy and findable', ok: true }, { t: 'To slow the computer' }, { t: 'To hide our work' }] },
        { q: 'Type a good name for a folder that holds your work:', type: 'type', placeholder: 'Practice Work', ok: 'Good. That is a clear folder name.' },
        { q: 'You open a file by…', type: 'pick', ok: 'Correct. Double-click to open it.', options: [{ t: 'Double-clicking it', ok: true }, { t: 'Right-clicking twice' }, { t: 'Pressing Space' }] },
        { q: 'Find practice: open the file you saved last lesson.', type: 'practice', minutes: 8, detail: 'Learner navigates to Documents and opens the file from a previous session. Staff prompts only if needed.', evidence: 'Learner locates and opens a saved file.' },
        { q: 'A folder inside another folder is sometimes called a…', type: 'pick', ok: 'Correct. A subfolder — a smaller box inside a bigger box.', options: [{ t: 'Subfolder', ok: true }, { t: 'Superfile' }, { t: 'Sidebar' }] },
        { q: 'Stretch: move or save a file into the practice folder.', type: 'practice', minutes: 8, detail: 'Use a safe test file. Staff supports the learner to place it inside the new folder.', evidence: 'Learner sees the file inside the folder.' },
      ],
    },
    {
      title: 'Practice: save and find',
      goal: 'Complete the full routine: create, save, close, and find again.',
      outcome: 'I can create a note, save it, close it, and find it again — mostly on my own.',
      tutor: 'In this lesson, we put the routine together. You will open Word, type a note, save it, close it, and find it again. This is a real independence skill, and we will take it one step at a time.',
      steps: ['Open Word', 'Type a short note', 'Save it in Documents', 'Close Word', 'If ready: find and reopen the note with no reminders'],
      carer: 'Step back for this lesson. Compare the prompt level on the first attempt with the second. Growing independence is the thing to celebrate here.',
      tasks: [
        { q: 'Warm-up: say the full routine before touching the computer.', type: 'practice', minutes: 5, detail: 'Create, type, save, close, find. Staff says it once, learner repeats or points to prompt cards.', evidence: 'Learner understands the sequence before starting.' },
        { q: 'Put the routine in order — what comes first?', type: 'pick', ok: 'Correct. We open the program first.', options: [{ t: 'Open the program', ok: true }, { t: 'Close the program' }, { t: 'Find the file' }] },
        { q: 'Type a short note:', type: 'type', placeholder: 'Today I practised saving my work.', ok: 'Great. That is ready to save.' },
        { q: 'What should happen before closing the file?', type: 'pick', ok: 'Correct. Save before closing so the work is not lost.', options: [{ t: 'Save first', ok: true }, { t: 'Close without saving' }, { t: 'Print it first' }, { t: 'Turn off the computer' }] },
        { q: 'Guided full routine.', type: 'practice', minutes: 14, detail: 'Open Word, type a note, save it in Documents, close Word, then reopen the file.', evidence: 'Full workflow completed with prompt level recorded.' },
        { q: 'After saving, where will you look to find the note?', type: 'pick', ok: 'Correct. In the Documents folder.', options: [{ t: 'Documents', ok: true, s: 'icon' }, { t: 'The Recycle Bin' }, { t: 'The taskbar' }] },
        { q: 'Type a clear name for your note:', type: 'type', placeholder: 'my practice note', ok: 'Good clear name.' },
        { q: 'Closing a saved file means the work is…', type: 'pick', ok: 'Correct. Safe — you can open it again any time.', options: [{ t: 'Safe and reopenable', ok: true }, { t: 'Gone forever' }, { t: 'Emailed away' }] },
        { q: 'Second attempt with fewer prompts.', type: 'practice', minutes: 12, detail: 'Repeat with a new file name. Staff waits longer before helping.', evidence: 'Compare prompt level with the first attempt.' },
        { q: 'Type one sentence for your second note:', type: 'type', placeholder: 'I saved and found my work.', ok: 'Excellent. That sentence fits today’s practice.' },
        { q: 'If you cannot find a file, a calm next step is…', type: 'pick', ok: 'Correct. Look in Documents, where we always save.', options: [{ t: 'Look in Documents', ok: true }, { t: 'Give up' }, { t: 'Delete everything' }] },
        { q: 'Type the word for keeping your work:', type: 'type', placeholder: 'save', answer: 'save', ok: 'Correct. Saving keeps your work.' },
        { q: 'Doing the routine with no reminders shows…', type: 'pick', ok: 'Correct. Growing independence — brilliant progress.', options: [{ t: 'Growing independence', ok: true }, { t: 'Nothing' }, { t: 'A broken computer' }] },
        { q: 'Independent challenge: full routine with a new name.', type: 'practice', minutes: 12, detail: 'Learner completes create–save–close–find alone as far as possible, with a fresh file name.', evidence: 'Record the lowest prompt level reached.' },
        { q: 'Reflection: tell staff which step was easiest and hardest.', type: 'practice', minutes: 5, detail: 'Use words, pointing or yes/no choices. Staff notes barriers and the next support step.', evidence: 'Reflection captured in support notes if useful.' },
      ],
    },
    {
      title: 'Word: type a sentence',
      goal: 'Open Word and write a complete sentence with a capital letter and full stop.',
      outcome: 'I can write a sentence with a capital at the start, spaces between words, and a full stop.',
      tutor: 'In this lesson, we use Word for real writing. A strong sentence starts with a capital letter, has spaces between words, and ends with a full stop. I will show you how to build it slowly.',
      steps: ['Open Microsoft Word', 'Click the blank page', 'Start with a capital letter', 'End with a full stop', 'If ready: write two connected sentences'],
      carer: 'Note the support needed for the cursor, capitals, spaces, and the full stop separately — they are different skills. Focus on meaning first, then accuracy.',
      tasks: [
        { q: 'Warm-up: open Word and find the blank page.', type: 'practice', minutes: 8, detail: 'Learner opens Word, clicks the page, and watches for the flashing cursor.', evidence: 'Learner can place the cursor on the page.' },
        { q: 'Choose the app used for documents.', type: 'pick', ok: 'Correct. Word is used for documents and letters.', options: [{ t: 'W', ok: true, s: 'icon-w' }, { t: 'X', s: 'icon-x' }, { t: 'Documents', s: 'icon' }, { t: 'Bin', s: 'icon' }] },
        { q: 'A sentence should start with a…', type: 'pick', ok: 'Correct. A capital letter starts a sentence.', options: [{ t: 'Capital letter', ok: true }, { t: 'Number' }, { t: 'Space' }] },
        { q: 'Which key helps make a capital letter?', type: 'pick', ok: 'Correct. Hold Shift for one capital letter.', options: [{ t: 'Shift', ok: true, s: 'key' }, { t: 'Space', s: 'key' }, { t: 'Backspace', s: 'key' }] },
        { q: 'Guided sentence building.', type: 'practice', minutes: 12, detail: 'Build one sentence together: capital letter, words, spaces and full stop.', evidence: 'Sentence is readable and complete.' },
        { q: 'A sentence usually ends with a…', type: 'pick', ok: 'Correct. A full stop ends a sentence.', options: [{ t: 'Full stop', ok: true }, { t: 'Capital letter' }, { t: 'Space' }] },
        { q: 'Type a full sentence:', type: 'type', placeholder: 'I am learning to use a computer.', ok: 'Excellent. That sentence is clear and complete.' },
        { q: 'Between each word we press…', type: 'pick', ok: 'Correct. Space makes the gap between words.', options: [{ t: 'Space', ok: true, s: 'key' }, { t: 'Enter', s: 'key' }, { t: 'Shift', s: 'key' }] },
        { q: 'Independent sentence attempt.', type: 'practice', minutes: 12, detail: 'Learner writes a sentence about something real: lunch, family, work, weather or today’s lesson.', evidence: 'Record whether they needed help with cursor, Shift, spacing or full stop.' },
        { q: 'Type a full practice sentence:', type: 'type', placeholder: 'I am learning digital skills.', ok: 'Good sentence. It has a clear meaning.' },
        { q: 'The flashing line shows…', type: 'pick', ok: 'Correct. Where your next letter will appear.', options: [{ t: 'Where letters appear', ok: true }, { t: 'The time' }, { t: 'The battery' }] },
        { q: 'Type a sentence about your day, starting with a capital:', type: 'type', placeholder: 'Today I feel good.', ok: 'Lovely — a real sentence about you.' },
        { q: 'To fix a wrong letter you press…', type: 'pick', ok: 'Correct. Backspace removes it, then retype.', options: [{ t: 'Backspace', ok: true, s: 'key' }, { t: 'Enter', s: 'key' }, { t: 'Shift', s: 'key' }] },
        { q: 'Read-back practice: read your sentence aloud.', type: 'practice', minutes: 6, detail: 'Learner reads (or has read back) their sentence, checking it makes sense and has a full stop.', evidence: 'Learner checks their own work for meaning.' },
        { q: 'Stretch: write a second sentence on a new line.', type: 'practice', minutes: 6, detail: 'Press Enter and add another sentence. Staff supports punctuation only after the idea is typed.', evidence: 'Two-line document created.' },
      ],
    },
    {
      title: 'Word: copy, paste and undo',
      goal: 'Select text, copy it, paste it, and undo a mistake.',
      outcome: 'I can select text and use copy, paste, and undo. I know undo can take me back.',
      tutor: 'In this lesson, we edit without starting again. Copy, paste, and undo are useful tools because they let you try things safely. If something changes by mistake, undo helps you go back.',
      steps: ['Select the word or sentence', 'Copy with Ctrl + C', 'Click where the copy should go', 'Paste with Ctrl + V', 'If ready: undo with Ctrl + Z'],
      carer: 'Teach one shortcut at a time. Say the action first, then the keys. Reassure the learner that undo makes mistakes safe.',
      tasks: [
        { q: 'Warm-up: select a word a few times.', type: 'practice', minutes: 8, detail: 'Practise selecting a word by double-clicking or dragging. Staff can use a large sample word.', evidence: 'Learner understands selected text changes appearance.' },
        { q: 'Before you copy, you first need to…', type: 'pick', ok: 'Correct. Select the text first.', options: [{ t: 'Select the text', ok: true }, { t: 'Close the file' }, { t: 'Print the page' }] },
        { q: 'Copy is Ctrl plus which letter?', type: 'pick', ok: 'Correct. Ctrl + C copies.', hint: 'C is for copy.', options: [{ t: 'C', ok: true, s: 'key' }, { t: 'V', s: 'key' }, { t: 'Z', s: 'key' }] },
        { q: 'Paste is Ctrl plus which letter?', type: 'pick', ok: 'Correct. Ctrl + V pastes.', options: [{ t: 'V', ok: true, s: 'key' }, { t: 'C', s: 'key' }, { t: 'B', s: 'key' }] },
        { q: 'Guided copy and paste.', type: 'practice', minutes: 12, detail: 'Select one word, copy it with Ctrl + C, click lower on the page and paste with Ctrl + V.', evidence: 'Same word appears twice in the document.' },
        { q: 'Undo is Ctrl plus which letter?', type: 'pick', ok: 'Correct. Ctrl + Z undoes the last change.', options: [{ t: 'Z', ok: true, s: 'key' }, { t: 'Y', s: 'key' }, { t: 'A', s: 'key' }] },
        { q: 'Which shortcut copies selected text?', type: 'pick', ok: 'Correct. Ctrl + C copies.', options: [{ t: 'Ctrl + C', ok: true, s: 'key' }, { t: 'Ctrl + V', s: 'key' }, { t: 'Ctrl + Z', s: 'key' }] },
        { q: 'Copy means the original text…', type: 'pick', ok: 'Correct. Stays where it is — a copy is made. (Cut is the one that removes it.)', options: [{ t: 'Stays where it is', ok: true }, { t: 'Is removed, like Cut' }, { t: 'Disappears' }, { t: 'Turns red' }] },
        { q: 'Undo practice.', type: 'practice', minutes: 8, detail: 'Make a safe mistake, such as pasting too many times, then use Ctrl + Z to undo it.', evidence: 'Learner sees that mistakes can be reversed.' },
        { q: 'Type the shortcut letter for paste:', type: 'type', placeholder: 'V', answer: 'v', ok: 'Correct. Ctrl + V pastes.' },
        { q: 'Undo is useful because it…', type: 'pick', ok: 'Correct. It takes you back, so mistakes are safe.', options: [{ t: 'Takes you back', ok: true }, { t: 'Deletes the file' }, { t: 'Turns off the screen' }] },
        { q: 'Type the shortcut letter for copy:', type: 'type', placeholder: 'C', answer: 'c', ok: 'Correct. Ctrl + C copies.' },
        { q: 'Which key do you hold with C, V or Z?', type: 'pick', ok: 'Correct. Hold Ctrl, then press the letter.', options: [{ t: 'Ctrl', ok: true, s: 'key' }, { t: 'Space', s: 'key' }, { t: 'Enter', s: 'key' }] },
        { q: 'Paste practice: copy a name and paste it twice.', type: 'practice', minutes: 8, detail: 'Learner selects a name, copies it, and pastes it on two new lines. Staff prompts one shortcut at a time.', evidence: 'Learner completes a copy-then-paste sequence.' },
        { q: 'Independent editing challenge.', type: 'practice', minutes: 10, detail: 'Learner copies a name, pastes it twice, then undoes one paste. Staff only prompts when needed.', evidence: 'Record which shortcut was remembered independently.' },
      ],
    },
    {
      title: 'Word: format text',
      goal: 'Make text easier to read using bold, italic, underline and colour.',
      outcome: 'I can select a word first, then make it bold, italic, underlined, or coloured.',
      tutor: 'In this lesson, we make important words stand out. First we choose the text, then we change it. I will show you bold, italic, underline, and colour using that simple rule: choose first, then change.',
      steps: ['Select the word first', 'Press B for bold', 'Press I for italic', 'Press U for underline', 'If ready: change the colour for a heading'],
      carer: 'The key habit is "select first". Note whether the learner remembered to select before formatting. Repeat: choose first, then change.',
      tasks: [
        { q: 'Warm-up: select text before changing it.', type: 'practice', minutes: 8, detail: 'Learner selects a word, then clicks away. Repeat until "choose first, change second" is clear.', evidence: 'Learner can select text intentionally.' },
        { q: 'The formatting rule is…', type: 'pick', ok: 'Correct. Choose first, then change.', options: [{ t: 'Choose first, then change', ok: true }, { t: 'Change first, then choose' }, { t: 'Never select' }] },
        { q: 'Which button makes text bold?', type: 'pick', ok: 'Correct. B makes text bold.', options: [{ t: 'B', ok: true, s: 'bold' }, { t: 'I', s: 'it' }, { t: 'U', s: 'ul' }] },
        { q: 'Which button makes text italic?', type: 'pick', ok: 'Correct. I makes text italic.', options: [{ t: 'I', ok: true, s: 'it' }, { t: 'B', s: 'bold' }, { t: 'U', s: 'ul' }] },
        { q: 'Guided formatting set.', type: 'practice', minutes: 12, detail: 'Apply bold, italic and underline to three different words. Undo one and apply it again.', evidence: 'Document shows at least three formatting changes.' },
        { q: 'Which button underlines text?', type: 'pick', ok: 'Correct. U underlines text.', options: [{ t: 'U', ok: true, s: 'ul' }, { t: 'B', s: 'bold' }, { t: 'I', s: 'it' }] },
        { q: 'Which button changes text colour?', type: 'pick', ok: 'Correct. The A colour button changes text colour.', options: [{ t: 'A Colour', ok: true, s: 'colour' }, { t: 'B', s: 'bold' }, { t: 'U', s: 'ul' }] },
        { q: 'Bold text is used to make a word…', type: 'pick', ok: 'Correct. Stand out and get noticed.', options: [{ t: 'Stand out', ok: true }, { t: 'Disappear' }, { t: 'Smaller' }] },
        { q: 'Colour practice.', type: 'practice', minutes: 10, detail: 'Select a heading or name and change its colour. Keep the colour readable.', evidence: 'Learner chooses and applies one text colour.' },
        { q: 'Type the rule for formatting:', type: 'type', placeholder: 'choose first then change', answer: 'choose', ok: 'Correct. Choose first, then change.' },
        { q: 'If you format without selecting first, usually…', type: 'pick', ok: 'Correct. Nothing changes — you must select first.', options: [{ t: 'Nothing changes', ok: true }, { t: 'The file deletes' }, { t: 'The computer beeps loudly' }] },
        { q: 'Type the letter for the bold button:', type: 'type', placeholder: 'B', answer: 'b', ok: 'Correct. B is for bold.' },
        { q: 'A readable colour on a white page is…', type: 'pick', ok: 'Correct. A dark colour shows up well on white.', options: [{ t: 'A dark colour', ok: true }, { t: 'Pale yellow' }, { t: 'White' }] },
        { q: 'Underline practice: underline one important word.', type: 'practice', minutes: 6, detail: 'Learner selects one key word and underlines it, then removes the underline to see the difference.', evidence: 'Learner applies and removes underline deliberately.' },
        { q: 'Independent mini-design.', type: 'practice', minutes: 10, detail: 'Learner formats a three-line note so the title stands out and key words are readable.', evidence: 'Staff records whether formatting choices were independent.' },
      ],
    },
    {
      title: 'Word: title and alignment',
      goal: 'Create a clear title, change the text size, and centre it on the page.',
      outcome: 'I can make a title bigger and bold, and centre it above my writing.',
      tutor: 'In this lesson, we make a page look professional. We will create a clear title, make it bigger and bold, centre it, and then keep the main writing underneath easy to read.',
      steps: ['Type a title at the top', 'Select the title', 'Choose a bigger font size', 'Make the title bold', 'If ready: centre the title'],
      carer: 'Note the support needed for selecting, sizing and alignment separately. Centre alignment is often the trickiest. Use a real document idea.',
      tasks: [
        { q: 'Warm-up: compare title and body text.', type: 'practice', minutes: 6, detail: 'Show a plain sentence and a title. Ask which one is easier to spot and why.', evidence: 'Learner recognises the title as larger or more prominent.' },
        { q: 'A title tells the reader…', type: 'pick', ok: 'Correct. What the page is about.', options: [{ t: 'What the page is about', ok: true }, { t: 'The time of day' }, { t: 'Nothing useful' }] },
        { q: 'For a bigger title, choose a…', type: 'pick', ok: 'Correct. A bigger font-size number makes bigger text.', options: [{ t: 'Bigger number', ok: true }, { t: 'Smaller number' }, { t: 'The bold button' }, { t: 'The colour button' }] },
        { q: 'To change the title only, you must first…', type: 'pick', ok: 'Correct. Select the title.', options: [{ t: 'Select the title', ok: true }, { t: 'Close Word' }, { t: 'Print the page' }] },
        { q: 'Guided title creation.', type: 'practice', minutes: 12, detail: 'Type a useful title, select it, make it bigger, make it bold and centre it.', evidence: 'Document has a clear title at the top.' },
        { q: 'Which alignment puts the title in the middle?', type: 'pick', ok: 'Correct. Centre alignment puts it in the middle.', options: [{ t: 'Left' }, { t: 'Centre', ok: true }, { t: 'Right' }] },
        { q: 'Type a title for a simple document:', type: 'type', placeholder: 'My Shopping List', ok: 'That title is clear and useful.' },
        { q: 'Making a title bold helps it…', type: 'pick', ok: 'Correct. Stand out from the writing below.', options: [{ t: 'Stand out', ok: true }, { t: 'Move down the page' }, { t: 'Turn into a list' }] },
        { q: 'Build a short document under the title.', type: 'practice', minutes: 12, detail: 'Add three short lines underneath the title. Practise returning to normal text size.', evidence: 'Title and body text are visually different.' },
        { q: 'Type a title for today’s document:', type: 'type', placeholder: 'My Weekly Plan', ok: 'Good. That is a practical title.' },
        { q: 'The three main alignments are left, centre and…', type: 'pick', ok: 'Correct. Right is the third alignment.', options: [{ t: 'Right', ok: true }, { t: 'Bold' }, { t: 'Up' }] },
        { q: 'Type the alignment that puts text in the middle:', type: 'type', placeholder: 'centre', answer: 'cent', ok: 'Correct. Centre alignment sits in the middle.' },
        { q: 'Body text under the title should be…', type: 'pick', ok: 'Correct. Smaller than the title, so the title stands out.', options: [{ t: 'Smaller than the title', ok: true }, { t: 'Bigger than the title' }, { t: 'The same as the title' }] },
        { q: 'Size practice: make a title big, then return text to normal.', type: 'practice', minutes: 6, detail: 'Learner enlarges the title, then selects the body text and sets a normal size.', evidence: 'Learner changes size deliberately for different text.' },
        { q: 'Stretch: align one line left, centre and right.', type: 'practice', minutes: 6, detail: 'Use alignment buttons to show how text moves. Return the final title to centre.', evidence: 'Learner identifies centre alignment.' },
      ],
    },
    {
      title: 'Word: lists, spell check and PDF',
      goal: 'Create a bulleted list, check spelling, and save a document as a PDF.',
      outcome: 'I can make a bulleted list, fix a spelling mistake, and save my work as a PDF.',
      tutor: 'In this lesson, we make information easier to share. We will use a bulleted list, notice spell-check suggestions, and save as a PDF so the work looks the same on other devices.',
      steps: ['Use the bullet button to make a list', 'Look for red wavy spelling lines', 'Right-click a word for suggestions', 'Choose File, Save As, then PDF', 'If ready: practise printing or sharing the PDF'],
      carer: 'Check the learner understands why a PDF is useful (it looks the same everywhere), not only how to make one. A PDF is useful for sending, printing or evidencing work.',
      tasks: [
        { q: 'Warm-up: choose a real topic for a list.', type: 'practice', minutes: 6, detail: 'Choose a real list: shopping, medication reminders, jobs, appointments or packing.', evidence: 'Learner chooses a meaningful list topic.' },
        { q: 'A list makes information…', type: 'pick', ok: 'Correct. Easier to read, one item per line.', options: [{ t: 'Easier to read', ok: true }, { t: 'Harder to read' }, { t: 'Invisible' }] },
        { q: 'Which option makes a neat list?', type: 'pick', ok: 'Correct. Bullets make a clear list.', options: [{ t: 'Bullets', ok: true }, { t: 'Bold only', s: 'bold' }, { t: 'Underline', s: 'ul' }, { t: 'A bigger size' }] },
        { q: 'On a bulleted list, each item goes on…', type: 'pick', ok: 'Correct. Its own line.', options: [{ t: 'Its own line', ok: true }, { t: 'All one line' }, { t: 'A new page each time' }] },
        { q: 'Guided bulleted list.', type: 'practice', minutes: 12, detail: 'Create a bulleted list with at least four items. Practise Enter for a new bullet.', evidence: 'List has multiple bullet points.' },
        { q: 'A red wavy line usually means…', type: 'pick', ok: 'Correct. It means check the spelling.', options: [{ t: 'Check the spelling', ok: true }, { t: 'The word is bold' }, { t: 'The word is a link' }] },
        { q: 'To see spelling suggestions you…', type: 'pick', ok: 'Correct. Right-click the underlined word.', options: [{ t: 'Right-click the word', ok: true }, { t: 'Delete the whole line' }, { t: 'Close Word' }] },
        { q: 'Spell-check practice.', type: 'practice', minutes: 10, detail: 'Type one deliberate spelling mistake, notice the red line, and choose a suggested correction.', evidence: 'Learner sees spelling support as helpful, not failure.' },
        { q: 'To share a document safely, save as…', type: 'pick', ok: 'Correct. PDF keeps the layout consistent.', options: [{ t: 'PDF', ok: true, s: 'key' }, { t: 'Music file', s: 'key' }, { t: 'Random folder', s: 'key' }] },
        { q: 'A PDF is useful because it…', type: 'pick', ok: 'Correct. Looks the same on every device.', options: [{ t: 'Looks the same everywhere', ok: true }, { t: 'Plays music' }, { t: 'Deletes itself' }] },
        { q: 'Type the file type that keeps a layout the same:', type: 'type', placeholder: 'PDF', answer: 'pdf', ok: 'Correct. PDF keeps the layout consistent.' },
        { q: 'A red wavy line is Word trying to…', type: 'pick', ok: 'Correct. Help you, not tell you off.', options: [{ t: 'Help you', ok: true }, { t: 'Tell you off' }, { t: 'Delete the word' }] },
        { q: 'Type a word you might put on a shopping list:', type: 'type', placeholder: 'milk', ok: 'Good — a clear list item.' },
        { q: 'List-building practice: make a four-item shopping list.', type: 'practice', minutes: 8, detail: 'Learner types four real items as a bulleted list, one per line, pressing Enter between them.', evidence: 'A tidy four-item list is created.' },
        { q: 'Save/share practice.', type: 'practice', minutes: 8, detail: 'Use Save As and choose PDF. Staff may stop before final saving if using a shared device.', evidence: 'Learner can find PDF in the save options.' },
      ],
    },
    {
      title: 'Excel: cells, rows and columns',
      goal: 'Recognise cells, rows, columns and the cell name in Excel.',
      outcome: 'I know each box is a cell, columns are letters and rows are numbers, and the first cell is A1.',
      tutor: 'In this lesson, we meet Excel. Excel is a grid made from cells. I will show you how columns, rows, and cell names work, starting with the first cell: A1.',
      steps: ['Open Microsoft Excel', 'Notice the grid of cells', 'Columns use letters across the top', 'Rows use numbers down the side', 'If ready: click A1 and move with arrow keys'],
      carer: 'Introduce Excel as a grid, not a writing page. Keep the language consistent: columns across, rows down. Use zoom if the grid feels busy.',
      tasks: [
        { q: 'Warm-up: point to rows, columns and cells.', type: 'practice', minutes: 8, detail: 'Use a blank spreadsheet. Learner points to a column letter, a row number and a cell.', evidence: 'Learner distinguishes letters across and numbers down.' },
        { q: 'Excel looks most like…', type: 'pick', ok: 'Correct. A grid of boxes, like squared paper.', options: [{ t: 'A grid of boxes', ok: true }, { t: 'A blank letter' }, { t: 'A photo' }] },
        { q: 'Each box in Excel is called a…', type: 'pick', ok: 'Correct. Each box is a cell.', options: [{ t: 'Cell', ok: true }, { t: 'Bag' }, { t: 'Page' }] },
        { q: 'Columns are named with…', type: 'pick', ok: 'Correct. Columns use letters across the top.', options: [{ t: 'Letters', ok: true }, { t: 'Numbers' }, { t: 'Colours' }, { t: 'Shapes' }] },
        { q: 'Guided navigation.', type: 'practice', minutes: 10, detail: 'Click A1, B1, A2 and C3. Use the name box or staff prompts to confirm each cell.', evidence: 'Learner reaches named cells with reduced support.' },
        { q: 'Rows are named with…', type: 'pick', ok: 'Correct. Rows use numbers.', options: [{ t: 'Numbers', ok: true }, { t: 'Letters' }, { t: 'Shapes' }] },
        { q: 'Choose the first cell in the top-left corner.', type: 'pick', ok: 'Correct. The first cell is A1.', options: [{ t: 'A1', ok: true, s: 'cell' }, { t: 'B2', s: 'cell' }, { t: 'C3', s: 'cell' }] },
        { q: 'A cell name is made of…', type: 'pick', ok: 'Correct. A letter and a number, like A1.', options: [{ t: 'A letter and a number', ok: true }, { t: 'Two numbers' }, { t: 'A colour and a word' }] },
        { q: 'Arrow-key practice.', type: 'practice', minutes: 10, detail: 'Start at A1 and move around the sheet using arrow keys. Say or point to the new cell name.', evidence: 'Learner uses arrow keys without losing place.' },
        { q: 'Type the name of the first top-left cell:', type: 'type', placeholder: 'A1', answer: 'a1', ok: 'Correct. A1 is the first cell.' },
        { q: 'Cell B3 means…', type: 'pick', ok: 'Correct. Column B, row 3.', options: [{ t: 'Column B, row 3', ok: true }, { t: 'Row B, column 3' }, { t: '3 cells' }] },
        { q: 'Type the letter used for the first column:', type: 'type', placeholder: 'A', answer: 'a', ok: 'Correct. Column A is the first column.' },
        { q: 'The box that shows the current cell name is the…', type: 'pick', ok: 'Correct. The Name Box, at the top-left.', options: [{ t: 'Name Box', ok: true }, { t: 'Recycle Bin' }, { t: 'Ribbon' }] },
        { q: 'Cell-finding practice: click cells as they are named.', type: 'practice', minutes: 8, detail: 'Staff names cells (A2, C1, B3) and the learner clicks each one, checking the Name Box.', evidence: 'Learner reaches named cells reliably.' },
        { q: 'Stretch: explain one cell name in your own words.', type: 'practice', minutes: 6, detail: 'Ask what C2 means: column C, row 2. Use pointing if spoken explanation is difficult.', evidence: 'Learner understands a cell reference as letter plus number.' },
      ],
    },
    {
      title: 'Excel: build a tidy table',
      goal: 'Enter simple data, add a header, widen a column and format money.',
      outcome: 'I can make headings, type my data underneath, and show prices as money.',
      tutor: 'In this lesson, we build a tidy Excel table. We will add headings, type simple data, make the headings stand out, widen a column, and show prices as money.',
      steps: ['Click cell A1', 'Type a column heading', 'Type items down the column', 'Make the header bold', 'If ready: format prices as currency'],
      carer: 'Pick a table topic that matters to the learner. Practise with realistic examples such as snacks, bus fares or weekly shopping. Note their confidence reading the table back.',
      tasks: [
        { q: 'Warm-up: choose a real table topic.', type: 'practice', minutes: 6, detail: 'Pick something useful: snacks and prices, bus times, chores, attendance or weekly spending.', evidence: 'Learner understands what the table is for.' },
        { q: 'A table keeps information…', type: 'pick', ok: 'Correct. Tidy and easy to read.', options: [{ t: 'Tidy', ok: true }, { t: 'Hidden' }, { t: 'Noisy' }] },
        { q: 'The top row of a table usually holds the…', type: 'pick', ok: 'Correct. The headings.', options: [{ t: 'Headings', ok: true }, { t: 'Totals' }, { t: 'Nothing' }] },
        { q: 'Type a useful table heading:', type: 'type', placeholder: 'Item', ok: 'Good. A clear heading starts a tidy table.' },
        { q: 'Guided data entry.', type: 'practice', minutes: 12, detail: 'Create headings in row 1, then enter at least five rows of simple data.', evidence: 'Table contains headings and multiple rows.' },
        { q: 'How should a header row stand out?', type: 'pick', ok: 'Correct. Bold headers are easier to scan.', options: [{ t: 'Bold', ok: true, s: 'bold' }, { t: 'Hidden' }, { t: 'Blank' }] },
        { q: 'To move down to the next cell you press…', type: 'pick', ok: 'Correct. Enter moves down to the next row.', options: [{ t: 'Enter', ok: true, s: 'key' }, { t: 'Shift', s: 'key' }, { t: 'Escape', s: 'key' }] },
        { q: 'Column width practice.', type: 'practice', minutes: 10, detail: 'Widen a column so the longest word can be read. Try dragging the boundary between column letters.', evidence: 'Learner sees that columns can be resized.' },
        { q: 'If a word is cut off, you should…', type: 'pick', ok: 'Correct. Widen the column so it fits.', options: [{ t: 'Widen the column', ok: true }, { t: 'Delete the word' }, { t: 'Close Excel' }] },
        { q: 'Which format is used for prices?', type: 'pick', ok: 'Correct. Currency is used for money.', options: [{ t: 'Currency', ok: true, s: 'key' }, { t: 'Percent', s: 'key' }, { t: 'Bold text', s: 'bold' }] },
        { q: 'Type a money heading for a table:', type: 'type', placeholder: 'Cost', ok: 'Good. Cost is a useful money heading.' },
        { q: 'Currency format shows a…', type: 'pick', ok: 'Correct. A money symbol, like £, before the number.', options: [{ t: 'Money symbol (£)', ok: true }, { t: 'Percent sign (%)' }, { t: 'Question mark (?)' }] },
        { q: 'Type an item you might put in a table:', type: 'type', placeholder: 'milk', ok: 'Good — a clear table item.' },
        { q: 'Header-bold practice: make the top row bold.', type: 'practice', minutes: 6, detail: 'Learner selects the heading row and applies bold so it stands out from the data.', evidence: 'Header row is visibly different from the data.' },
        { q: 'Format prices.', type: 'practice', minutes: 10, detail: 'Enter simple prices and apply currency formatting. Discuss why money formatting helps.', evidence: 'At least one number is shown as a price.' },
      ],
    },
    {
      title: 'Excel: formulas and totals',
      goal: 'Use a simple formula and AutoSum to calculate a total.',
      outcome: 'I can write a formula that starts with =, and total a column with AutoSum.',
      tutor: 'In this lesson, Excel does the maths for us. A formula starts with an equals sign. We will type a simple formula, use cell names, and finish with AutoSum to total a column.',
      steps: ['Every formula starts with =', 'Add two numbers, for example =2+3', 'Use AutoSum to add a column', 'Press Enter to show the answer', 'If ready: explain what the total means'],
      carer: 'This completes the course. Celebrate the journey from the power button to writing formulas. Ask the learner to describe one thing they can now do more independently.',
      tasks: [
        { q: 'Warm-up: formula confidence.', type: 'practice', minutes: 6, detail: 'Show that formulas are instructions for Excel. Say: "equals means Excel, please work this out."', evidence: 'Learner recognises formulas start with equals.' },
        { q: 'A formula is best described as…', type: 'pick', ok: 'Correct. An instruction that tells Excel to work something out.', options: [{ t: 'An instruction for Excel', ok: true }, { t: 'A picture' }, { t: 'A folder' }] },
        { q: 'Every Excel formula starts with which sign?', type: 'pick', ok: 'Correct. Formulas start with the equals sign =.', options: [{ t: '=', ok: true, s: 'key' }, { t: '+', s: 'key' }, { t: '#', s: 'key' }, { t: '£', s: 'key' }] },
        { q: 'Type a formula to add 2 and 3:', type: 'type', placeholder: '=2+3', answer: '2+3', ok: 'Correct. That formula gives 5.', hint: 'Start with = and then type 2+3.' },
        { q: 'Guided simple formula.', type: 'practice', minutes: 10, detail: 'Type =2+3, press Enter, then change the numbers and try again.', evidence: 'Learner sees the result change after pressing Enter.' },
        { q: 'After typing a formula, you press…', type: 'pick', ok: 'Correct. Enter shows the answer.', options: [{ t: 'Enter', ok: true, s: 'key' }, { t: 'Shift', s: 'key' }, { t: 'Escape', s: 'key' }] },
        { q: 'Which sign means "add" in a formula?', type: 'pick', ok: 'Correct. The plus sign adds numbers.', options: [{ t: '+', ok: true, s: 'key' }, { t: '?', s: 'key' }, { t: '=', s: 'key' }] },
        { q: 'Cell formula practice.', type: 'practice', minutes: 12, detail: 'Put two numbers in cells, then add them with a formula such as =A1+B1. Use simple values first.', evidence: 'Formula uses cell names, not only typed numbers.' },
        { q: 'A formula like =A1+B1 adds…', type: 'pick', ok: 'Correct. The numbers in cells A1 and B1.', options: [{ t: 'The values in A1 and B1', ok: true }, { t: 'The letters A and B' }, { t: 'Nothing' }] },
        { q: 'Type a formula that adds 4 and 6:', type: 'type', placeholder: '=4+6', answer: '4+6', ok: 'Correct. That is a real formula.' },
        { q: 'Which option adds a whole column for you?', type: 'pick', ok: 'Correct. AutoSum adds the selected numbers.', options: [{ t: 'AutoSum', ok: true, s: 'key' }, { t: 'Bold', s: 'bold' }, { t: 'Percent', s: 'key' }] },
        { q: 'AutoSum is quicker because it…', type: 'pick', ok: 'Correct. Totals a whole column with one click.', options: [{ t: 'Totals a column in one click', ok: true }, { t: 'Deletes the column' }, { t: 'Changes the colour' }] },
        { q: 'Type the sign every formula starts with:', type: 'type', placeholder: '=', answer: '=', ok: 'Correct. Every formula starts with =.' },
        { q: 'AutoSum practice: total three prices.', type: 'practice', minutes: 10, detail: 'Enter three prices, select the cell below, and use AutoSum to total them. Press Enter to see the answer.', evidence: 'Learner produces a correct column total.' },
        { q: 'Celebrate: complete the course and view your certificate.', type: 'practice', minutes: 6, detail: 'Return to iLearn, mark the lesson complete, and open the certificate together. Ask the learner what they are most proud of.', evidence: 'Course completed and certificate viewed with the learner.' },
      ],
    },
  ],
};
